### ISSUE TITLE
TypeORMのLeftJoinができない

### ISSUE THREAD

**Issue by ryo-n-cell** [ryo-n-cell/SorenaAPI#5]
やりたいこと：question_tableを基としてstatus_countsにLeftJoinしたい。

「question_table.questions_id」と「status_counts.question_id」
で1対多で設定済

・テーブル図
![スクリーンショット 2022-02-25 145200](https://user-images.githubusercontent.com/57280888/155661953-3f7c647e-c310-4679-888e-f94dfff9fe4d.png)

そのため、以下のクエリをTypeORMで生成したい。
```
SELECT question_table.*, status_counts.status 
FROM question_table 
LEFT JOIN status_counts ON question_table.questions_id = status_counts.question_id 
where question_table.category_id = 1;
```

が以下のコードでは生成できない。

該当コード
https://github.com/ryo-n-cell/SorenaAPI/blob/c836215236b3d96b85079d11b45adc95572673a6/src/index.ts#L43-L58

設定Entity
https://github.com/ryo-n-cell/SorenaAPI/blob/c836215236b3d96b85079d11b45adc95572673a6/src/entity/question_table.ts#L1-L18

https://github.com/ryo-n-cell/SorenaAPI/blob/c836215236b3d96b85079d11b45adc95572673a6/src/entity/status_counts.ts#L1-L29

エラーログ
```
TypeError: Cannot read property 'joinColumns' of undefined
    at C:\Users\Ryouta Nakamura\Desktop\workingNow\aruaruApp\SorenaAPI\src\query-builder\SelectQueryBuilder.ts:1549:61
    at Array.map (<anonymous>)
    at SelectQueryBuilder.createJoinExpression (C:\Users\Ryouta Nakamura\Desktop\workingNow\aruaruApp\SorenaAPI\src\query-builder\SelectQueryBuilder.ts:1520:57)
    at SelectQueryBuilder.getQuery (C:\Users\Ryouta Nakamura\Desktop\workingNow\aruaruApp\SorenaAPI\src\query-builder\SelectQueryBuilder.ts:57:21)      
    at SelectQueryBuilder.QueryBuilder.getQueryAndParameters (C:\Users\Ryouta Nakamura\Desktop\workingNow\aruaruApp\SorenaAPI\src\query-builder\QueryBuilder.ts:446:28)
    at SelectQueryBuilder.<anonymous> (C:\Users\Ryouta Nakamura\Desktop\workingNow\aruaruApp\SorenaAPI\src\query-builder\SelectQueryBuilder.ts:2112:40) 
    at step (C:\Users\Ryouta Nakamura\Desktop\workingNow\aruaruApp\SorenaAPI\node_modules\tslib\tslib.js:143:27)
    at Object.next (C:\Users\Ryouta Nakamura\Desktop\workingNow\aruaruApp\SorenaAPI\node_modules\tslib\tslib.js:124:57)
    at C:\Users\Ryouta Nakamura\Desktop\workingNow\aruaruApp\SorenaAPI\node_modules\tslib\tslib.js:117:75
    at new Promise (<anonymous>)
```

「 Cannot read property 'joinColumns' of undefined」という事は分かりますが、なぜjoinColumnsが定義されていないのか？
TypeORMのEntityのリレーション設定周りの理解できていないままトライ＆エラーを繰り返しているのでその部分を含め教えて頂きたいです。
（以下のIssueも見ましたがまだ理解できていないです、、、）

全体リポジトリ
https://github.com/ryo-n-cell/SorenaAPI/tree/question

参考document
https://typeorm.io/#/find-options

参考Issue
https://github.com/typeorm/typeorm/issues/2016
https://github.com/typeorm/typeorm/issues/2587

**Comment by ryo-n-cell** [comment]
以下修正を頂いて、確認後プルリクをしたのでこのIssueは閉じる。

https://github.com/ryo-n-cell/SorenaAPI/pull/6
